name = "ChromeProfileFormat"
uuid = "b19f0eae-10f4-4ff0-9df2-b48cd85f6b2e"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "1.0.1-DEV"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JSON = "0.20, 0.21"
julia = "1"

[targets]
test = ["Test"]
